import pandas as pd
import numpy as np
from ta.momentum import RSIIndicator, StochasticOscillator
from ta.trend import MACD, EMAIndicator, SMAIndicator
from ta.volatility import BollingerBands, AverageTrueRange
from ta.volume import OnBalanceVolumeIndicator

def add_technical_indicators(df):
    """
    Adds comprehensive technical indicators to the dataframe.
    """
    df = df.copy()
    
    # Ensure numeric types
    numeric_cols = ['open', 'high', 'low', 'close', 'volume']
    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    # Momentum Indicators
    # RSI
    rsi_indicator = RSIIndicator(close=df["close"], window=14)
    df["rsi"] = rsi_indicator.rsi()

    # Stochastic Oscillator
    stoch_indicator = StochasticOscillator(high=df["high"], low=df["low"], close=df["close"], window=14, smooth_window=3)
    df["stoch_k"] = stoch_indicator.stoch()
    df["stoch_d"] = stoch_indicator.stoch_signal()

    # Trend Indicators
    # MACD
    macd_indicator = MACD(close=df["close"], window_slow=26, window_fast=12, window_sign=9)
    df["macd"] = macd_indicator.macd()
    df["macd_signal"] = macd_indicator.macd_signal()
    df["macd_diff"] = macd_indicator.macd_diff()

    # Moving Averages
    df["sma_20"] = SMAIndicator(close=df["close"], window=20).sma_indicator()
    df["ema_12"] = EMAIndicator(close=df["close"], window=12).ema_indicator()
    df["ema_26"] = EMAIndicator(close=df["close"], window=26).ema_indicator()

    # Volatility Indicators
    # Bollinger Bands
    bb_indicator = BollingerBands(close=df["close"], window=20, window_dev=2)
    df["bb_upper"] = bb_indicator.bollinger_hband()
    df["bb_lower"] = bb_indicator.bollinger_lband()
    df["bb_middle"] = bb_indicator.bollinger_mavg()

    # ATR
    atr_indicator = AverageTrueRange(high=df["high"], low=df["low"], close=df["close"], window=14)
    df["atr"] = atr_indicator.average_true_range()

    # Volume Indicators
    # OBV
    obv_indicator = OnBalanceVolumeIndicator(close=df["close"], volume=df["volume"])
    df["obv"] = obv_indicator.on_balance_volume()

    # Additional Features
    # Log Return
    df["log_return"] = np.log(df["close"] / df["close"].shift(1))
    
    # High-Low Range
    df["hl_range"] = df["high"] - df["low"]
    
    # Rolling Volatility (20-period)
    df["rolling_vol_20"] = df["log_return"].rolling(window=20).std()

    # Drop NaN values generated by indicators
    df = df.dropna()
    
    return df
