import pandas as pd
from ta.momentum import RSIIndicator
from ta.trend import MACD

def add_technical_indicators(df):
    """
    Adds RSI and MACD to the dataframe.
    """
    df = df.copy()
    
    # Ensure numeric types
    for col in ['open', 'high', 'low', 'close', 'volume']:
        df[col] = pd.to_numeric(df[col])

    # RSI
    rsi_indicator = RSIIndicator(close=df["close"], window=14)
    df["rsi"] = rsi_indicator.rsi()

    # MACD
    macd_indicator = MACD(close=df["close"], window_slow=26, window_fast=12, window_sign=9)
    df["macd"] = macd_indicator.macd()
    df["macd_signal"] = macd_indicator.macd_signal()
    df["macd_diff"] = macd_indicator.macd_diff()

    # Drop NaN values generated by indicators
    df = df.dropna()
    
    return df
